@WebApplicationPractica_HostAddress = http://localhost:5278

### peticion para verificar el estado del servicio

GET {{WebApplicationPractica_HostAddress}}/api/Product/status
Accept: application/json

### peticion para obtener un producto por su id
GET {{WebApplicationPractica_HostAddress}}/api/Product/1
Accept: application/json

### peticion para obtener todos los productos
GET {{WebApplicationPractica_HostAddress}}/api/Product
accept: application/json

### peticion para crear un nuevo producto
POST {{WebApplicationPractica_HostAddress}}/api/Product 
Content-Type: application/json

{
  "name": "Laptop HP",
  "category": "Electronics",
  "price": 999.99
}

### peticion para actualizar un producto existente

PUT {{WebApplicationPractica_HostAddress}}/api/Product/4
Content-Type: application/json

{
  "id" : 4,
  "name": "Laptop Asus",
  "category": "Electronics",
  "price": 12
}

### peticion para eliminacion logica de un producto por su id

DELETE {{WebApplicationPractica_HostAddress}}/api/Product/3
Content-Type: application/json

    